[build]
  ignore = "false"

[[redirects]]
  from = "/slowniki/wojewodztwa"
  to = "https://api.cepik.gov.pl/slowniki/wojewodztwa"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/pojazdy"
  to = "https://api.cepik.gov.pl/pojazdy"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/"
  status = 200